# Travis CI configuration file.

language: php
cache:
  paths:
  - vendor/

php:
- 8.1


before_script:
  # Start up a web server.
 - php -S localhost:8085 --docroot /src &>/dev/null&
# Install Codeception.
# Doing this last gives the webdriver and server time to start up.
- composer install --prefer-source

script:
- vendor/bin/codecept run