# Travis CI configuration file.

language: php
cache:
  apt: true
php:
- 8.1
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

before_script:
# Doing this last gives the webdriver and server time to start up.
- composer install --prefer-source

script:
- vendor/bin/codecept run