# Travis CI configuration file.

language: php
addons:
  chrome: beta
before_install:
  - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"
cache:
  apt: true
php:
- 8.1

before_script:
# Install Codeception.
# Doing this last gives the webdriver and server time to start up.
- composer install --prefer-source

script:
- vendor/bin/codecept run