# Travis CI configuration file.

language: php
cache:
  apt: true
php:
- 8.1

before_script:
# Start up a web server.
- php -S 127.0.0.1:8888 -t /src >/dev/null 2>&1 &
- sleep 3
# Start up the webdriver.
- phantomjs --webdriver=4444 >/dev/null 2>&1 &
- sleep 3
# Install Codeception.
# Doing this last gives the webdriver and server time to start up.
# - composer install --prefer-source

script:
- vendor/bin/codecept run