# Travis CI configuration file.

language: php

cache:
  directories:
    - /vendor/
php:
- 8.1

before_script:

# Install Codeception.
# Doing this last gives the webdriver and server time to start up.
- composer install --prefer-source

script:
- vendor/bin/codecept run