# Services
services:

  # Nginx Service
  nginx:
    image: nginx:1.19
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/php
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  # PHP Service
  php:
    image: php:8.1-fpm
    working_dir: /var/www/php
    volumes:
      - ./src:/var/www/php

# Más info en
# https://tech.osteel.med/posts/docker-for-local-web-development-part-1-a-basic-lemp-stack

# Lanzar con
# docker-compose up -d

# Ver los logs con
# docker-compose logs -f