name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Start Containers
        run: docker-compose up -d --build

      - name: Install dependencies
        run: docker container exec -it php composer update

      - name: Run test
        run: docker container exec -it php ./vendor/bin/codecept run

    
